  
name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  vyos:
    runs-on: ubuntu-latest
    env:
      RELEASE_EMAIL: m+vyos-builds@silvenga.com
      RELEASE_VERSION: 1.3.X-slvn-1
      RELEASE_BRANCH: equuleus
      BUILD_IMAGE: vyos/vyos-build:equuleus

    steps:
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
          version: latest
      - uses: actions/checkout@v2
        with:
          repository: vyos/vyos-build
          ref: ${{ env.RELEASE_BRANCH }}

      - name: Build iso
        run: |
          docker pull ${{ env.BUILD_IMAGE }}
          docker run --privileged \
            -v $(pwd):/vyos \
            -w /vyos \
            ${{ env.BUILD_IMAGE }} \
            bash -c './configure --architecture amd64 --build-type release --build-by "${{ env.RELEASE_EMAIL }}" --version "${{ env.RELEASE_VERSION }}" --debian-mirror http://deb.debian.org/debian/ --custom-package vyos-1x-smoketest && sudo make iso'
            mv build/live-image-amd64.hybrid.iso build/${{ env.RELEASE_BRANCH }}-${{ env.RELEASE_VERSION }}-amd64.hybrid.iso

      - uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          name: ${{ env.RELEASE_BRANCH }}-${{ env.RELEASE_VERSION }}-amd64.hybrid.iso
          path: build
          container: ${{ env.RELEASE_BRANCH }}